sudo: required
services:
  -docker

before_install:
  - docker build -t lwalton99/react-test -f ./client/Docerfile.dev ./client

script:
  - docker run lwalton99/react-test npm test -- --coverage

after_success:
  - docker build -t lwalton99/multi-client ./client
  - docker build -t lwalton99/multi-nginx ./nginx
  - docker build -t lwalton99/multi-server ./server
  - docker build -t lwalton99/multi-worker ./worker
